[package]
edition = "2024"
authors = ["Francisco A. B. Sampaio <franciscoabsampaio@gmail.com>"]
name = "spark-connect"
version = "0.3.0"
description = "Rust client for Apache Spark Connect."
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/spark-connect"
repository = "https://github.com/franciscoabsampaio/spark-connect"
homepage = "https://github.com/franciscoabsampaio/spark-connect"
keywords = ["spark", "connect", "sql", "data", "client"]
categories = ["api-bindings", "database"]

[dependencies]
apache_spark_connect = { package = "apache-spark-connect", version = "4.2.0" }
arrow = { version = "58", default-features = false }
chrono = { version = "0.4.42", optional = true }
futures-core = "0.3"
tokio = { version = "1.47", features = ["rt", "sync"] }

[dev-dependencies]
regex = "1.11.3"
tokio = { version = "1.47", features = ["rt-multi-thread", "macros"] }

[[example]]
name = "databricks"

[features]
chrono = ["dep:chrono"]

[profile.release]
codegen-units = 1 # Improves optimizations
lto = true
opt-level = "z"   # "z" for size, "3" for maximum performance
panic = "abort"   # Abort on panic instead of unwinding - smaller binaries and slightly faster
