name: Build, Test, and Draft Release

on:
  pull_request:
    branches:
      - release
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/release.yaml'

env:
  PROJECT_NAME: spark-connect

jobs:
  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep -Po '(?<=^version = ")[^"]*' Cargo.toml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f v${{ steps.get_version.outputs.version }}
          git push -f origin v${{ steps.get_version.outputs.version }}

  test-and-package:
    needs: [tag-version]
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
    permissions:
      actions: read
      id-token: write
      contents: write
    outputs:
      hash_b64: ${{ steps.hash.outputs.hash_b64 }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Spark Connect Server container instance
        run: docker run -d -p 15002:15002 ${{ github.repository_owner }}/spark-connect-server:delta
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Test crate
        run: |
          cargo test --locked spark-connect
      
      # Package crate (creates target/package/*.crate)
      - name: Package crate
        run: cargo package
        
      # Create draft release with crate
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.PROJECT_NAME }} v${{ needs.tag-version.outputs.version }}"
          tag_name: v${{ needs.tag-version.outputs.version }}
          body: |
            Included in this release:
            
            - Crate tarball for crates.io (`*.crate`).
            - Provenance.
          draft: true
          files: target/package/*.crate
          overwrite_files: true

      # Generate attestations for each artifact
      - name: Attest build artifacts
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: target/package/*.crate
          show-summary: true
